"""Generic single-database configuration.

Revision ID: 645f949f3626
Revises: 0001_initial
Create Date: 2025-11-25 14:30:20.333530

"""
from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.add_column('messages', sa.Column('likes', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('messages', sa.Column('dislikes', sa.Integer(), nullable=False, server_default='0'))
    op.create_table(
        'message_reactions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('message_id', sa.Integer(), sa.ForeignKey('messages.id'), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('value', sa.String(length=8), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.UniqueConstraint('user_id', 'message_id', name='uq_message_user_reaction'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_reactions')
    op.drop_column('messages', 'dislikes')
    op.drop_column('messages', 'likes')
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
